

default_platform(:android)

platform :android do
    if File.exist?('../../.env')
      open('../../.env', 'r').readlines.each do |l|
        kv = l.split('=')
        ENV[kv[0]] = kv[1].chomp
      end
    end
  version_code = nil
  version_name = nil


  before_all do
    version_name = sh "grep 'version:' ../../pubspec.yaml | awk '{ print $2 }' | tr -d '\n'"
    version_code = 203 + Integer(sh("git rev-list HEAD --first-parent --count"))
  end

  lane :alpha do
    flavor = "alpha"
    build(
      flavor: flavor,
    )
    apkPath = "../build/app/outputs/apk/#{flavor}/release/app-#{flavor}-release.apk"
    appcenter_upload(
      api_token: ENV["ALPHA_APPCENTER_API_TOKEN"],
      owner_name: ENV["ALPHA_APPCENTER_OWNER_NAME"],
      app_name: "CloudNet-Alpha-Android",
      file: apkPath
    )
  end

  lane :beta do
    build(
      flavor: "beta",
    )
  end

  lane :store do
    build(
      flavor: "store",
    )
  end

  desc "Build app with Flutter tool and archive with Gym"
  lane :build do |options|
    flavor = options[:flavor]

    # build with flutter tool
    sh ("cd ../.. && flutter build apk --release --flavor #{flavor} -t lib/main_#{flavor}.dart --build-number=#{version_code}")
  end
end
